### ISSUE TITLE
ARM Images not being built 

### ISSUE THREAD

**Issue by fabioaraujopt** [crossplane-contrib/provider-terraform#120]
ARM images are not being built, if you look into:

https://hub.docker.com/r/crossplane/provider-terraform-controller/tags

Manifest only have amd64 images.

Also here 

https://hub.docker.com/r/crossplane/provider-terraform-controller-arm64/tags

Only amd64 images..

**Comment by ytsarev** [comment]
thanks for the report.

We need to update the packaging mechanism to use a combined(controller+CRD) image following the latest approach, it might inherently fix the issue.

**Comment by fabioaraujopt** [comment]
I believe this is the cause for this error right??

`cannot initialize Terraform configuration: fork/exec /bin/terraform: exec format error`

**Comment by ytsarev** [comment]
yes, looks like it

**Comment by fabioaraujopt** [comment]
Amazing job @ytsarev !

**Comment by loafoe** [comment]
Hi @ytsarev @fabioaraujopt the issue seems to be that Hashicorp does not provide `arm64` Terraform Docker images at all, so the terraform binary would always be the `amd64` one. I created a PR #126 which pulls in some parts of the upjet based build process to deal with this. Essentially, it downloads release binaries instead of using the Hashicorp base image. I'm testing this on on an rpi4 based cluster and so far so good.
