### ISSUE TITLE
[Question] What is the benefit of this integration

### ISSUE THREAD

**Issue by gyliu513** [crossplane-contrib/provider-terraform#9]
### What environment did it happen in?
Crossplane version: 

Thanks for creating this integration, can anyone share some motivation why a user to not use terraform directly but use this integration with crossplane?

**Comment by negz** [comment]
Hi @gyliu513! Thanks for the question. I see the benefit of this provider as twofold:

1. Offering folks who are using Terraform today a gradual migration path to Crossplane.
2. Allowing folks who are using Crossplane to leverage Terraform's broad ecosystem of resources that Crossplane does not yet support.

More generally, the reason someone would use this integration with Crossplane would be all of the same reasons someone might use Crossplane to manage their infrastructure; e.g. leaning into API driven, always on control planes with a strong separation of concerns.

**Comment by negz** [comment]
As to how this provider might help with migration - what I’m imaging is that folks could take their trusted, existing Terraform modules and put them behind a Crossplane composite resource. This would potentially help with the migration because:

1. You’re only using a little bit of Crossplane - just the composition frontend - at first so it’s a lower risk up front.
1. You immediately enable opinionated, API driven self service on top of your existing Terraform modules.
1. You can write a second, equivalent composition that uses native Crossplane managed resources and slowly migrate your users over to that to gain confidence in Crossplane.

i.e. I see this as enabling a gradual way to migrate from (for example) a widely used “opinionated RDS instance” Terraform module to the Crossplane equivalent.

**Comment by gyliu513** [comment]
thanks @negz , this make sense, let me close it.
